export const ReadyQuestions: ReadonlyArray<string> = [
  'autocomplete',
  'news-feed-facebook',
  'poll-widget',
  'image-carousel',
  'photo-sharing-instagram',
  'e-commerce-amazon',
  'chat-application-messenger',
  'travel-booking-airbnb',
  'email-client-outlook',
  'dropdown-menu',
  'modal-dialog',
  'pinterest',
  'video-streaming-netflix',
  'rich-text-editor',
  'collaborative-editor-google-docs',
];
