export type EmailKey =
  'CHECKOUT_FIRST_TIME' | 'CHECKOUT_MULTIPLE_TIMES' | 'INTERVIEWS_COMPLETED_SOME_QUESTIONS' | 'INTERVIEWS_WELCOME_EMAIL_24_HOURS' | 'INTERVIEWS_WELCOME_EMAIL_IMMEDIATE' | 'PAYMENT_FAILED';
