export type EmailKey =
  | 'INTERVIEWS_CHECKOUT_FIRST_TIME'
  | 'INTERVIEWS_CHECKOUT_MULTIPLE_TIMES'
  | 'INTERVIEWS_PROGRESS'
  | 'INTERVIEWS_WELCOME_EMAIL_24_HOURS'
  | 'INTERVIEWS_WELCOME_EMAIL_IMMEDIATE'
  | 'PAYMENT_FAILED';
