// Keep this file simple because it needs to run on both server and client.
export const ProjectsReputationPointsConfig = {
  DISCUSSIONS_COMMENT: 20,
  DISCUSSIONS_COMMENT_VOTE: 10,
  PROFILE_COMPLETE: 50,
  PROFILE_FIELD_PER_OPTIONAL: 100,
  PROFILE_FIELD_REQUIRED: 50,
  PROFILE_SIGN_UP: 20,
  SESSION_FIRST: 20,
  SUBMISSION_SKILL_DEFAULT: 5,
  SUBMISSION_TECH_STACK: 2,
  SUBMISSION_VOTE: 10,
};
