export const LETTER_GUESS_STATE = {
  INDETERMINATE: 'INDETERMINATE',
  ABSENT: 'ABSENT',
  PRESENT: 'PRESENT',
  CORRECT: 'CORRECT',
};

export const LETTER_GUESS_STATE_PRIORITY = {
  INDETERMINATE: 1,
  ABSENT: 2,
  PRESENT: 3,
  CORRECT: 4,
};

export const GAME_STATE = {
  IN_PROGRESS: 'IN_PROGRESS',
  GUESSED_CORRECTLY: 'GUESSED_CORRECTLY',
  NO_MORE_GUESSES: 'NO_MORE_GUESSES',
};
