module.exports = {
  root: [
    'introduction',
    {
      type: 'category',
      label: 'Coding interview',
      collapsed: false,
      items: [
        'javascript-utility-function',
        'build-front-end-user-interfaces',
        'algorithms',
      ],
    },
    {
      type: 'category',
      label: 'Quiz/trivia interview',
      items: [
        'trivia',
        'javascript-questions',
        'css-questions',
        'html-questions',
      ],
    },
    {
      type: 'category',
      label: 'System design interview',
      collapsed: false,
      items: [
        'front-end-system-design',
        'front-end-system-design-ui-components',
        'front-end-system-design-applications',
      ],
    },
    'behavioral',
    'resume',
    {
      type: 'category',
      label: 'Interview questions 🔥',
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Company interview questions',
        slug: '/company-interview-questions',
      },
      items: [
        'companies/google-front-end-interview-questions',
        'companies/meta-front-end-interview-questions',
        'companies/amazon-front-end-interview-questions',
        'companies/microsoft-front-end-interview-questions',
        'companies/apple-front-end-interview-questions',
        'companies/netflix-front-end-interview-questions',
        'companies/uber-front-end-interview-questions',
        'companies/airbnb-front-end-interview-questions',
        'companies/linkedin-front-end-interview-questions',
        'companies/openai-front-end-interview-questions',
        'companies/bytedance-tiktok-front-end-interview-questions',
        'companies/stripe-front-end-interview-questions',
        'companies/shopify-front-end-interview-questions',
        'companies/adobe-front-end-interview-questions',
        'companies/coinbase-front-end-interview-questions',
        'companies/roblox-front-end-interview-questions',
        'companies/atlassian-front-end-interview-questions',
        'companies/salesforce-front-end-interview-questions',
        'companies/reddit-front-end-interview-questions',
        'companies/pinterest-front-end-interview-questions',
        'companies/palantir-front-end-interview-questions',
        'companies/doordash-front-end-interview-questions',
        'companies/dropbox-front-end-interview-questions',
        'companies/lyft-front-end-interview-questions',
        'companies/canva-front-end-interview-questions',
        'companies/discord-front-end-interview-questions',
        'companies/rippling-front-end-interview-questions',
        'companies/ramp-front-end-interview-questions',
        'companies/robinhood-front-end-interview-questions',
        'companies/ebay-front-end-interview-questions',
        'companies/oracle-front-end-interview-questions',
        'companies/twitter-front-end-interview-questions',
        'companies/squarespace-front-end-interview-questions',
        'companies/mozilla-front-end-interview-questions',
        'companies/ethos-front-end-interview-questions',
        'companies/harvey-front-end-interview-questions',
      ],
    },
  ],
};
